# Generated by Django 6.0.2 on 2026-02-10 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizer',
            old_name='phone_Number',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phone_Number',
            new_name='phone_number',
        ),
    ]
