# Generated by Django 6.0.2 on 2026-02-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0002_rename_phone_number_organizer_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
