# Generated by Django 6.0.2 on 2026-02-12 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0003_organizer_password_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='id',
        ),
    ]
